services:
  postfix:
    image: as247/postfix
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
    ports:
      - "2525:25"
    volumes:
      - postfix_data:/data
    networks:
      - mail_network

volumes:
  postfix_data:
networks:
  mail_network:
    driver: bridge